### ISSUE TITLE
Cannot Export to sif from Inkscape

### ISSUE THREAD

**Issue by MyriaCore** [synfig/synfig#1591]
**Synfig version & platform**:

```
Inkscape: 1.0 (4035a4fb49, 2020-05-01)
Synfig Studio: 1.2.2
OS: Manjaro Linux x86_64 
Kernel: 5.4.52-1-MANJARO 
Shell: bash 5.0.18 
CPU: Intel i7-8650U (8) @ 4.200GHz 
GPU: Intel UHD Graphics 620 
Memory: 8527MiB / 15762MiB 
```

**Issue description**:

Installed synfig via [Arch official repositories](https://www.archlinux.org/packages/community/x86_64/synfigstudio/). Inkscape is [also installed via Arch official repositories](https://www.archlinux.org/packages/extra/x86_64/inkscape/). Tried to save my svg as a `.sif` from Inkscape, and I get this error:

```
Traceback (most recent call last):
  File "synfig_output.py", line 1336, in <module>
    SynfigExport().run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 123, in run
    self.save_raw(self.effect())
  File "synfig_output.py", line 1057, in effect
    width = get_dimension(svg.get("width", 1024))
  File "/usr/share/inkscape/extensions/synfig_prepare.py", line 435, in get_dimension
    elif s[-1] == "%":
TypeError: 'int' object is not subscriptable
```

X-Posted from https://github.com/nikitakit/svg2sif/issues/6

**Comment by MyriaCore** [comment]
Closing this as it's an inkscape issue, not a synfig issue. This is now being tracked at [inkscape/extensions#278](https://gitlab.com/inkscape/extensions/-/issues/278)
