### ISSUE TITLE
Removing last Waypoint of an Exported Value crashes Synfig Studio

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1701]
**Synfig version & platform**:
master 88e56d2
openSUSE 15.2

**Issue description**:
1) Create a new animation
2) Draw a `Rectangle` on Canvas
3) Go to the `Parameters` Panel and select `Point 1`, right-click `Export Value`
4) Enable animation editing mode
5) Create a couple of Waypoints for `Point 1` exported value

At this point the exported value has some waypoints

6) Go to the `Library` Panel, under `ValueBase Nodes` remove the exported value Waypoints

After deleting the last Waypoint, Synfig Studio crashes consistently.

The expected behavior should be that the Value becomes constant (the same state when added without any Waypoints).

**Comment by rodolforg** [comment]
I reproduce it with Rectangle (shape) layer, but not with region-type layer.
Backtrace:

```
#6  0x0000555555df62b9 in Gtk::TreeRow::get_value<synfigapp::ValueDesc>(Gtk::TreeModelColumn<synfigapp::ValueDesc> const&) const (this=0x7fffffff9530, column=...) at /usr/include/gtkmm-3.0/gtkmm/treeiter.h:604
#7  0x0000555555df5d50 in Gtk::TreeValueProxy<synfigapp::ValueDesc>::operator synfigapp::ValueDesc() const (this=0x7fffffff9480) at /usr/include/gtkmm-3.0/gtkmm/treeiter.h:558
#8  0x0000555555fe3377 in studio::CanvasTreeStore::get_value_vfunc(Gtk::TreeIter const&, int, Glib::ValueBase&) const (this=0x555558633c00, iter=..., column=3, value=...)
    at /home/rodolfo/projetos/synfig-puro/synfig-studio/src/gui/trees/canvastreestore.cpp:334
#9  0x00007ffff6687b1e in Gtk::TreeModel_Class::get_value_vfunc_callback(_GtkTreeModel*, _GtkTreeIter*, int, _GValue*) () at /usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
```

```
#127 0x000055555618ad98 in studio::CanvasViewUIInterface::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    (this=0x555558c20e50, err="Remover Ponto de passagem: Empty ID") at /home/rodolfo/projetos/synfig-puro/synfig-studio/src/gui/canvasview.cpp:289
#128 0x00007ffff7e4d75f in synfigapp::Action::System::perform_action(etl::handle<synfigapp::Action::Base>) (this=0x555558db4cb0, action=...)
    at /home/rodolfo/projetos/synfig-puro/synfig-studio/src/synfigapp/action_system.cpp:144
#129 0x00007ffff7e6f848 in synfigapp::CanvasInterface::waypoint_remove(etl::handle<synfig::ValueNode>, synfig::Waypoint) (this=0x555558b05e20, value_node=..., waypoint=...)
    at /home/rodolfo/projetos/synfig-puro/synfig-studio/src/synfigapp/canvasinterface.cpp:1220
#130 0x000055555617c1cb in remove_waypoints(std::set<synfig::Waypoint, std::less<synfig::UniqueID>, std::allocator<synfig::Waypoint> >, etl::loose_handle<synfigapp::CanvasInterface>)
    (waypoints=std::set with 1 element = {...}, canvas_interface=...) at /home/rodolfo/projetos/synfig-puro/synfig-studio/src/gui/canvasview.cpp:2920
#131 0x000055555619fad4 in sigc::pointer_functor2<std::set<synfig::Waypoint, std::less<synfig::UniqueID>, std::allocator<synfig::Waypoint> >, etl::loose_handle<synfigapp::CanvasInterface>, void>::operator()(std::set<synfig::Waypoint, std::less<synfig::UniqueID>, std::allocator<synfig::Waypoint> > const&, etl::loose_handle<synfigapp::CanvasInterface> const&) const (this=0x555557d43b80, _A_a1=..., _A_a2=...)
    at /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h:147
```
