### ISSUE TITLE
The files get corrupted and cannot be opened again.

### ISSUE THREAD

**Issue by Gilraiser** [synfig/synfig#1706]
**Synfig version & platform**:
V1.5.0 in Archlinux 64x
Revision: 20200913
Branch: master
Revision ID: f1d830a 
Built on Sep 14 2020

**Issue description**:
The files get corrupted and won't open again. The program closes when trying to open the file again. Occurs in files with few layers or with many layers, whether or not they include skeleton layers. Attached notices when run from terminal emulator. I also attach the corrupt file.

I hope it is useful. Thanks for the excellent support.

[CorruptedFile.sifz.zip](https://github.com/synfig/synfig/files/5229864/CorruptedFile.sifz.zip)
[Console-Message.txt](https://github.com/synfig/synfig/files/5229872/Console-Message.txt)

**Comment by FirasH** [comment]
Did you copy some Layers from a different animation?

**Comment by Gilraiser** [comment]
Hello, in this file yes. But in another file I made before, I only had one layer made with a bezier tool.

**Comment by Gilraiser** [comment]
Hi. I did several tests, and what I could observe is that the error is generated when layers of files that were created with the synfig development version are copied before the revision with ID 2beffbe. In files made with the development version f1d830a this failure does not happen. I attach four files. The first two are made with the development version f1d830a from scratch; a file with animation made up of a single object was created first, which was copied to a new file. Then I did the same but with a synfig file created with revision ID 2beffbe called Coin-01 and Coin-02.

Thank you very much for your attention

[01.sifz.zip](https://github.com/synfig/synfig/files/5235579/01.sifz.zip)
[02.sifz.zip](https://github.com/synfig/synfig/files/5235580/02.sifz.zip)
[Coin-01.sifz.zip](https://github.com/synfig/synfig/files/5235581/Coin-01.sifz.zip)
[Coin-02.sifz.zip](https://github.com/synfig/synfig/files/5235582/Coin-02.sifz.zip)

**Comment by rodolforg** [comment]
Developer note:
Problem is related to connecting/linking a Placeholder_ValueNode to `bline` parameter of an `AdvancedOutline` layer.
AdvancedOutline will try to call a value of this value node in `Advanced_Outline::connect_bline_to_wplist(etl::loose_handle<ValueNode> x)`

Why is it still a placeholder at that point in some cases?

Backtrace log:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff4dfa546 in __GI_abort () at abort.c:79
#2  0x00007ffff4dfa42f in __assert_fail_base
    (fmt=0x7ffff126b5e5 "%s%s%s:%u: %s%sAssertiva “%s” falhou.\n%n", assertion=0x7ffff762534f "0", file=0x7ffff7625188 "/home/rodolfo/projetos/synfig-puro/synfig-core/src/synfig/valuenode.cpp", line=540, function=<optimized out>) at assert.c:92
#3  0x00007ffff4e09222 in __GI___assert_fail
    (assertion=0x7ffff762534f "0", file=0x7ffff7625188 "/home/rodolfo/projetos/synfig-puro/synfig-core/src/synfig/valuenode.cpp", line=540, function=0x7ffff76252f8 "virtual synfig::ValueBase synfig::PlaceholderValueNode::operator()(synfig::Time) const") at assert.c:101
#4  0x00007ffff71f4eb7 in synfig::PlaceholderValueNode::operator()(synfig::Time) const (this=0x555557ee6c40) at /home/rodolfo/projetos/synfig-puro/synfig-core/src/synfig/valuenode.cpp:540
#5  0x00007ffff754ae9f in synfig::ValueNode_Composite::operator()(synfig::Time) const (this=0x555557ee49f0, t=...)
    at /home/rodolfo/projetos/synfig-puro/synfig-core/src/synfig/valuenodes/valuenode_composite.cpp:314
#6  0x00007ffff7561ba4 in synfig::ValueNode_DynamicList::operator()(synfig::Time) const (this=0x5555565b1600, t=...)
    at /home/rodolfo/projetos/synfig-puro/synfig-core/src/synfig/valuenodes/valuenode_dynamiclist.cpp:671
#7  0x00007ffff760ba9b in synfig::ValueNode_WeightedAverage::operator()(synfig::Time) const (this=0x5555565b1600, t=...)
    at /home/rodolfo/projetos/synfig-puro/synfig-core/src/synfig/valuenodes/valuenode_weightedaverage.cpp:104
#8  0x00007ffff75306d6 in synfig::ValueNode_BLine::get_blinepoint(__gnu_cxx::__normal_iterator<synfig::ValueNode_DynamicList::ListEntry const*, std::vector<synfig::ValueNode_DynamicList::ListEntry, std::allocator<synfig::ValueNode_DynamicList::ListEntry> > >, synfig::Time) const (this=0x5555565cae00, current=Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer': 
Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer': 

    {<synfig::UniqueID> = {id_ = 238}, times = {<std::set<synfig::TimePoint, std::less<synfig::TimePoint>, std::allocator<synfig::TimePoint> >> = std::set with 0 elements, <No data fields>}, value_node = {<etl::handle<synfig::ValueNode>> = {obj = 0x5555565b1600}, prev_ = 0x0, next_ = 0x0}, timing_info = empty std::__cxx11::list, index = 0, parent_ = {obj = 0x5555565cae00}}, t=...)
    at /home/rodolfo/projetos/synfig-puro/synfig-core/src/synfig/valuenodes/valuenode_bline.cpp:939
#9  0x00007ffff752dd5b in synfig::ValueNode_BLine::operator()(synfig::Time) const (this=0x5555565cae00, t=...) at /home/rodolfo/projetos/synfig-puro/synfig-core/src/synfig/valuenodes/valuenode_bline.cpp:581
#10 0x00007fffce0befb4 in Advanced_Outline::connect_bline_to_wplist(etl::loose_handle<synfig::ValueNode>) (this=0x555557edfe70, x=...)
    at /home/rodolfo/projetos/synfig-puro/synfig-core/src/modules/mod_geometry/advanced_outline.cpp:856
#11 0x00007fffce0beb40 in Advanced_Outline::connect_dynamic_param(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, etl::loose_handle<synfig::ValueNode>)
    (this=0x555557edfe70, param="bline", x=...) at /home/rodolfo/projetos/synfig-puro/synfig-core/src/modules/mod_geometry/advanced_outline.cpp:815
#12 0x00007ffff7191fed in synfig::CanvasParser::parse_layer(xmlpp::Element*, etl::handle<synfig::Canvas>) (this=0x7fffffffd060, element=0x555557edc240, canvas=...)
    at /home/rodolfo/projetos/synfig-puro/synfig-core/src/synfig/loadcanvas.cpp:2995
```
