### ISSUE TITLE
Preferences dialog segmentation fault after quitting synfigstudio

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#2275]
**Describe the bug**
Preferences dialog causes segmentation fault when quitting synfigstudio.

**To Reproduce**
1. Open synfigstudio from terminal/command prompt
2. Open Edit>Preferences... dialog
3. Close dialog
4. Quit synfigstudio
5. Segmentation fault

**Expected behavior**
Clean exit without segmentation fault.

**Screenshots**
-nil-

**System information:**
 - OS: Fedora Linux
 - OS version: 34
 - Commit ID: bd50192679428ee10371c2a78d072e7bd4b731cd

**Additional comments**
GDB backtrace:
```gdb
Thread 1 "synfigstudio" received signal SIGSEGV, Segmentation fault.
0x00007ffff7261c39 in gtk_switch_state_flags_changed () from /lib64/libgtk-3.so.0
(gdb) bt
#0  0x00007ffff7261c39 in gtk_switch_state_flags_changed () at /lib64/libgtk-3.so.0
#1  0x00007ffff68822cc in g_cclosure_marshal_VOID__FLAGSv () at /lib64/libgobject-2.0.so.0
#2  0x00007ffff68a183a in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#3  0x00007ffff68a1983 in g_signal_emit () at /lib64/libgobject-2.0.so.0
#4  0x00007ffff73077cb in gtk_widget_propagate_state.lto_priv () at /lib64/libgtk-3.so.0
#5  0x00007ffff72f9d37 in gtk_widget_update_state_flags.lto_priv () at /lib64/libgtk-3.so.0
#6  0x00007ffff72ffc9f in gtk_widget_unparent () at /lib64/libgtk-3.so.0
#7  0x00007ffff7169cf8 in gtk_grid_remove () at /lib64/libgtk-3.so.0
#8  0x00007ffff688265e in g_cclosure_marshal_VOID__OBJECTv () at /lib64/libgobject-2.0.so.0
#9  0x00007ffff68a183a in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#10 0x00007ffff68a1983 in g_signal_emit () at /lib64/libgobject-2.0.so.0
#11 0x00007ffff70d4365 in gtk_container_remove () at /lib64/libgtk-3.so.0
#12 0x00007ffff73069e8 in gtk_widget_dispose.lto_priv () at /lib64/libgtk-3.so.0
#13 0x00007ffff6885a76 in g_object_run_dispose () at /lib64/libgobject-2.0.so.0
#14 0x00007ffff7d741d0 in Gtk::Object::_release_c_instance() () at /lib64/libgtkmm-3.0.so.1
#15 0x00007ffff7d1a6cb in Gtk::Switch::~Switch() () at /lib64/libgtkmm-3.0.so.1
#16 0x0000000000820078 in studio::Dialog_Setup::~Dialog_Setup() (this=0x1d579a0, __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at ../synfig-studio/src/gui/dialogs/dialog_setup.cpp:118
#17 0x0000000000820332 in studio::Dialog_Setup::~Dialog_Setup() (this=0x1d579a0, __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at ../synfig-studio/src/gui/dialogs/dialog_setup.cpp:118
#18 0x0000000000624911 in studio::App::~App() (this=0x7fffffffd9b0, __in_chrg=<optimized out>) at ../synfig-studio/src/gui/app.cpp:1795
#19 0x00000000005f9bfa in main(int, char**) (argc=0, argv=0x7fffffffde38) at ../synfig-studio/src/gui/main.cpp:138
```

**Comment by ice0** [comment]
Duplicate: https://github.com/synfig/synfig/issues/1661
