### ISSUE TITLE
Segfault on pressing Esc while rotating a rectangle

### ISSUE THREAD

**Issue by torgash-ivanblch** [synfig/synfig#470]
**Synfig version & platform**:
(we're more likely to help if you're using latest development builds)
1.3.4 appimage, Linux Mint 18.3 x64, Intel Core i3/6GBRAM/intel video
**Issue description**:
Steps to reproduce:
1. Draw a rectangle with an outline and (optional) region. 
2. Select all nodes and pick up rotation tool
3. Rotate the object no matter what node selected, no matter whether "Allow scale" is checked or not.
4. While rotating, press Escape on keyboard.

./bin//launch.sh: строка 64:  7615 Segmentation fault                  "$BASE_DIR/bin/synfigstudio.wrapper" "$@"

that's all I get on that step in terminal.

**Comment by caryoscelus** [comment]
Crashes on any usage of rotate tool + escape for me, not necessarily of rectangle.

Backtrace:
```
Thread 1 "synfigstudio" received signal SIGSEGV, Segmentation fault.
DuckDrag_Combo::duck_drag (this=0x555557831930, duckmatic=0x55555738f0e0, vector=...) at ../src/gui/states/state_normal.cpp:425
425                                     (*iter)->set_trans_point(positions[i]+vect, time);
(gdb) bt
#0  0x00005555559ab32a in DuckDrag_Combo::duck_drag(studio::Duckmatic*, synfig::Vector const&) (this=0x555557831930, duckmatic=0x55555738f0e0, vector=...) at ../src/gui/states/state_normal.cpp:425
#1  0x000055555588bb69 in studio::WorkArea::on_drawing_area_event(_GdkEvent*) (this=0x55555738f0c0, event=0x555557626d20)
    at ../src/gui/workarea.cpp:2009
#2  0x00007ffff7a3682b in  () at /usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#3  0x00007ffff628915b in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#4  0x00007ffff458af9d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff459db25 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff45a5e1f in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff45a6e9f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff63d3ad5 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff62860ee in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff6288268 in gtk_main_do_event () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007ffff5d953e5 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#12 0x00007ffff5dc6bb2 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#13 0x00007ffff42b1fa7 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff42b21e0 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff42b24f2 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff6287345 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x0000555555746668 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at ../src/gui/main.cpp:125
```

**Comment by morevnaproject** [comment]
Oh, my apologies - I have tested the wrong commit. Re-testing again...

**Comment by morevnaproject** [comment]
OK, I did tested on 627b6ce1c1 -  no crash. But the issue (https://youtu.be/Hgt_q_5rwTk) still persists.

@ice0 Would you willing to continue on fixing or should we close this now?

**Comment by ice0** [comment]
@morevnaproject I am continue to fixing, please check https://github.com/synfig/synfig/commit/ee77221724881fea4d066e708a51b810f98b61f6

**Comment by morevnaproject** [comment]
Shipped in version 1.3.7 - https://www.synfig.org/2018/05/14/synfig-studio-1-3-7-released/
