### ISSUE TITLE
SVG import fails (gradient?)

### ISSUE THREAD

**Issue by JasperKuiper** [synfig/synfig#554]
**Synfig version & platform**:
1.2 (tested on 1.3.8 as well), Win10

**Issue description**:
Importing attached SVG fails to nothing being shown. 

SVG was created in Affinity Designer, exported to SVG.

Also imported it in Inkscape, save to SIF and tried to open that --> Synfig crashed!

I have no issues in my workflow with other SVG objects from AD, but those do not contain gradients. Hence my conclusion it might be related to gradients ;-)

My general workflow is using AD (sorry to say I moved away from Inkscape, but for me this works better, pls no OSS rants, I like Inkscape, it works well most of the time, but not for everything). Majority of my AD work has different objectives, but some I'd like to re-use in Synfig. Because of that, re-creating in Synfig seems cumbersome atm.

[svg-test.zip](https://github.com/synfig/synfig/files/2071133/svg-test.zip)

**Comment by ice0** [comment]
Hello, Jasper!
Which version of Windows you are using (32/64 bit)? Because i checked both Synfig 32 and 64-bit versions and they didn't crush, but i can test only on Windows 10 64 for now. Also i want to mention that not all SVG shapes and properties are currently implemented in Synfig (this feature is already planned, just need more time). And again that is nice what you are working in Affinity Designer because we need to have more testing SVG files written by different programs (they can have slighly different formats).

**Comment by JasperKuiper** [comment]
Forgot to mention, W10 64-bit.

Just to be clear, the crashing occurs when importing the SIF after converting it from SVG.

When opening that original SVG, I can't see the shape, that's my main issue.

NB Happy to test with files from AD :-)

**Comment by amicalmant** [comment]
Any news? I have also issue with File > Save as.. Synfig:

Traceback (most recent call last):
  File "synfig_output.py", line 1344, in <module>
    e.affect(output=False)
  File "inkex.py", line 283, in affect
    self.effect()
  File "synfig_output.py", line 1053, in effect
    SynfigPrep.effect(self)
  File "synfig_prepare.py", line 483, in effect
    propagate_attribs(self.document.getroot())
  File "synfig_prepare.py", line 383, in propagate_attribs
    dw = get_dimension(node.get("width", vw))
  File "synfig_prepare.py", line 455, in get_dimension
    elif s[-1] == "%":
TypeError: 'float' object has no attribute '__getitem__'

Platform W10-64bit.
File opened: https://openclipart.org/detail/173001/quebec-map

**Comment by morevnaproject** [comment]
Hello @amicalmant. Please note that original author of this issue has problems with importing SVG file. From your post it looks like you have problems with exporting SVG file from Inkscape. Am I correct?

**Comment by amicalmant** [comment]
Oops! Sorry for the confusion. Let's recap:

- First, I tried to import the SVG file linked above but it failed (a new layer but no object that I can see and manipulate).
- Second, I read the *** manual.
- Third, I opened this SVG file in Inkscape in order to save it as explained in Synfig format. It is upon saving that I encountered the error detailed above.
- Fourth, I cannot import a synfig file that I was not able to create! ;-)

**Comment by morevnaproject** [comment]
@amicalmant  Since the exporter code is a part of Inkscape, I recommend to report it here - https://gitlab.com/inkscape/inkscape/

**Comment by IbanRothschild** [comment]
It seems that inkscape have a full SVG 2.0 implementation. Thing that is not normal or neither done by the librsvg so... If you use gradients ¿or fonts? without convert them to Path (and sometimes either) it does not understand the file...

I propose to show a border when an object-layer is selected to see where it is... Play an error sound. And discover if inkscape have its own conversion library...

**Comment by IbanRothschild** [comment]
Been able to work around doing this :
https://forums.synfig.org/t/inkscape-text-saved-as-synfig-file/4427/9

The steps are:
- path>object to path
- ungroup
- union
- save as sif

I been able to import text, linear gradients and circular gradients.

I been unable to import mesh gradients or patterns.

But there is a problem with cache... When you import a file, its loaded directly from the file but cached so if you change that file and import it again, it doesn't change. You need to close the program and open it again to see the changes. If you don't know that caching problem you can be wrong thinking that was an unsuccessful import.

**Comment by MyriaCore** [comment]
> First, I tried to import the SVG file linked above but it failed (a new layer but no object that I can see and manipulate).

I'm running into this and it's super maddening. Anyone know the source of this?

**Comment by veermetri05** [comment]
Exporting .sif from Inkscape (Save as -> Synfig file) Doesn't support export for gradients you have to recreate them in Synfig, moreover if the issue is with exporter of Inkscape Synfig cannot help.
