### ISSUE TITLE
suggestion: add Lottie export format

### ISSUE THREAD

**Issue by ec1oud** [synfig/synfig#704]
It seems popular, and a good animation format for the web and for mobile devices (but I just discovered it ;-)  I haven't found a proper spec for the JSON but there are open-source viewers, and JSON schema files here https://github.com/airbnb/lottie-web/tree/master/docs/json

**Comment by adampiskorski** [comment]
I think this would be a killer feature, as otherwise to have a nice modern pipeline for animations on web + mobile you would need Adobe AE.
Synfig could certainly reduce the barrier to entry and keep the pipeline in the open source world.

**Comment by ThobyV** [comment]
I support this move too. This would be very useful to have in synfig as also the web community Is large and svg-based animation on the web is growing. The thought of Having to use a great tool like synfig to make animations for the web makes me happy. 

May I ask, What are the core requirements that could make this happen.

**Comment by morevnaproject** [comment]
We need someone who can code a converter from .sif (Synfig format) to Lottie. This could be done in simple language, like Python.

This task requires knowledge of .sif format (this is just XML and easy to understand) and Lottie format (can be figured out from 
https://github.com/airbnb/lottie-web/tree/master/docs/json).

**Comment by dinolinjob** [comment]
I want to work on this issue.

**Comment by dinolinjob** [comment]
I want to implement this feature. Can I work on this one?

**Comment by ThobyV** [comment]
> We need someone who can code a converter from .sif (Synfig format) to Lottie. This could be done in simple language, like Python.
> 
> This task requires knowledge of .sif format (this is just XML and easy to understand) and Lottie format (can be figured out from
> https://github.com/airbnb/lottie-web/tree/master/docs/json).

This would mean writing a Python converter that parses XML into structured JSON. Lottie uses JSON and uses a Javascript interface so it's works well for the web.

**Comment by ThobyV** [comment]
Am I right to assume this?

**Comment by AnishGG** [comment]
Hi,
I am Anish from IIIT Hyderabad. I would like to contribute to this project in GSOC. I was going through the idea list and this seems interesting. Could anyone help me get started with this?

**Comment by morevnaproject** [comment]
@ThobyV Yes, you right. I think this can be implemented as Python plugin - https://wiki.synfig.org/Doc:Plugins

@dinolinjob @AnishGG welcome to the tread! I suggest to start by implementing a demo plugin that does some very simple conversion. I.e. converts some Synfig file with one simple layer (Rectangle or Circle or Image) to Lottie JSON.

**Comment by morevnaproject** [comment]
@dinolinjob @AnishGG @ThobyV  Before starting, please let me know which simple layer you choose to implement - so we make sure each one is taking different task. ^__^

**Comment by ThobyV** [comment]
@morevnaproject I think I'll go with a rectangle svg shape. I will make sure to update us here on my progress. :smile:

**Comment by dinolinjob** [comment]
@morevnaproject I will go with a circle.

**Comment by JagsPvr** [comment]
@morevnaproject  I am interested either. I'll go with the circle layer Synfig file. I will make sure to update you here. Most of my stuff is on Gitlab with id prasadPVR.

**Comment by morevnaproject** [comment]
Hi @JagsPvr ! The Circle layer task is already allocated to @dinolinjob. Please choose some other layer type. I suggest to take Image Layer or Star Layer (https://wiki.synfig.org/Star_Layer).

**Comment by morevnaproject** [comment]
This might be helpful - https://wiki.synfig.org/Sif_Format

**Comment by AnishGG** [comment]
@morevnaproject, I will go with the star layer.

**Comment by JagsPvr** [comment]
> Hi @JagsPvr ! The Circle layer task is already allocated to @dinolinjob. Please choose some other layer type. I suggest to take Image Layer or Star Layer (https://wiki.synfig.org/Star_Layer).

Ok... I will go with Image Layer.

**Comment by dinolinjob** [comment]
Which parameter from synfig file format should be referenced to   **"$ref": "#/properties/valueKeyframe"** in lottie json format?

**Comment by morevnaproject** [comment]
@dinolinjob Are you referring to this? - https://github.com/airbnb/lottie-web/blob/master/docs/json/properties/valueKeyframe.json

**Comment by morevnaproject** [comment]
For everyone: Important information about this project - https://forums.synfig.org/t/gsoc-2019-export-for-web/9507/17?u=konstantindmitriev

**Comment by ThobyV** [comment]
Truly the information from the page is awesome. I think it may be possible to export simple SVG-only animations and work on other issues on time. The lottie library does not seem to support all AE effects itself. Anyways I made this simple animation in synfig (Exported svg as .sif from Inkscape)_for testing the exporter which I will  be really happy if it animates on the web. I love the web and being a developer there it will be cool to have synfig do that, 

![synfarrow](https://user-images.githubusercontent.com/26300284/53792119-3cefc180-3f2b-11e9-80fc-1be0a6be7f95.gif)

**Comment by dinolinjob** [comment]
> @dinolinjob Are you referring to this? - https://github.com/airbnb/lottie-web/blob/master/docs/json/properties/valueKeyframe.json

Yeah, @morevnaproject I want to know what is the parameter for "k", "x", "ix" in synfig format?

**Comment by morevnaproject** [comment]
@ThobyV On SVG topic: I remember one user requested the possibility to export frames from Synfig into SVG image - https://www.facebook.com/synfig.org/posts/10156102720090920?comment_id=10156104482200920

> being able to export individual frames as svg files would be great for mechandising my characters without having to repose them using inkscape but by snyfig outputing to svg format would mean synfig could be used to setup poses for my characters inside synfig and if we could output individual frames as svg i think that would really help when i finish my project and attempt to create a merchandisable product in t shirts and mug printing of my characters 

@dinolinjob Sorry, I do not see  "k", "x", "ix" in https://github.com/airbnb/lottie-web/blob/master/docs/json/properties/valueKeyframe.json ^_^"
Can you please clarify what do you mean?

**Comment by dinolinjob** [comment]
> @ThobyV On SVG topic: I remember one user requested the possibility to export frames from Synfig into SVG image - https://www.facebook.com/synfig.org/posts/10156102720090920?comment_id=10156104482200920
> 
> > being able to export individual frames as svg files would be great for mechandising my characters without having to repose them using inkscape but by snyfig outputing to svg format would mean synfig could be used to setup poses for my characters inside synfig and if we could output individual frames as svg i think that would really help when i finish my project and attempt to create a merchandisable product in t shirts and mug printing of my characters
> 
> @dinolinjob Sorry, I do not see "k", "x", "ix" in https://github.com/airbnb/lottie-web/blob/master/docs/json/properties/valueKeyframe.json ^_^"
> Can you please clarify what do you mean?

Sorry @morevnaproject  "k", "x", "ix" in [https://github.com/airbnb/lottie-web/blob/master/docs/json/properties/value.json](https://github.com/airbnb/lottie-web/blob/master/docs/json/properties/value.json)

**Comment by morevnaproject** [comment]
@dinolinjob I am not very familiar with Lottie format yet, so I cannot say for sure.

But, as far as I can see, https://github.com/airbnb/lottie-web/blob/master/docs/json/properties/value.json describes just an arbitrary value of some parameter. I.e., Circle Layer has Radius Parameter, which is defined by some value. This is what https://github.com/airbnb/lottie-web/blob/master/docs/json/properties/value.json defines. The "k" parameter seems to be defines the value itself.

I recommend to try constructing simple Lottie JSON file first, to understand how it works. Also, you can check some demos here - https://github.com/airbnb/lottie-web/tree/master/demo (you might want to use JSON prettifier to improve readability - https://jsonformatter.curiousconcept.com/).
For specific questions, you might want to contact Lottie authors via - https://github.com/airbnb/lottie-web/blob/master/demo/adrock/data.json
Finally, you can try to create simple Lottie JSON files by exporting from AE (Adobe gives free trial versions of AE - https://www.adobe.com/products/aftereffects/free-trial-download.html).

**Comment by dinolinjob** [comment]
Thanks @morevnaproject I have created a simple lottie json by exporting from AE via bodymovin.
Now, I 'm mapping the required parameters between sif and json.

**Comment by susmita97** [comment]
> This might be helpful - https://wiki.synfig.org/Sif_Format

Is there any layer task that I can start working on that has not been assigned yet?

**Comment by morevnaproject** [comment]
Hi @susmita97! Glad to see you here. I suggest you to take an Image Layer. ^__^

**Comment by susmita97** [comment]
> Hi @susmita97! Glad to see you here. I suggest you to take an Image Layer. ^__^

Yes I will start working on it right away.

**Comment by susmita97** [comment]
Has anyone tried using the ElementTree provided by the standard library in python for parsing?

**Comment by susmita97** [comment]
> Hi @susmita97! Glad to see you here. I suggest you to take an Image Layer. ^__^

Can I share the code I have been working on here?It's not complete yet but I guess that will only be of help.

**Comment by morevnaproject** [comment]
Hi @susmita97! This is highly encouraged! You can push code to a branch in your GitHub account and make a PR to this repository (just as @AnishGG did - https://github.com/synfig/synfig/pull/756). ^__^

**Comment by morevnaproject** [comment]
For everyone interested: if you need usage samples of Lottie, I can suggest to examine samples at https://lottiefiles.com/

Here is a simple animation for example - https://lottiefiles.com/4913-menu-icon

**Comment by susmita97** [comment]
> Hi @susmita97! This is highly encouraged! You can push code to a branch in your GitHub account and make a PR to this repository (just as @AnishGG did - #756). ^__^

Thank you I will do that

**Comment by susmita97** [comment]
> Hi @susmita97! This is highly encouraged! You can push code to a branch in your GitHub account and make a PR to this repository (just as @AnishGG did - #756). ^__^

Also should I share my pre-proposal with you?Could you provide me with a few suggestions about the format and other things?

**Comment by morevnaproject** [comment]
@susmita97 

The best is to share pre-proposal privately by mailing me using PM on forums or via https://www.synfig.org/contact/ .

Application template can be found at the bottom of this page - https://summerofcode.withgoogle.com/organizations/6502365465673728/

**Comment by susmita97** [comment]
> @susmita97
> 
> The best is to share pre-proposal privately by mailing me using PM on forums or via https://www.synfig.org/contact/ .
> 
> Application template can be found at the bottom of this page - https://summerofcode.withgoogle.com/organizations/6502365465673728/

Thank you :)

**Comment by amanbora** [comment]
Hi, I am interested in working on this feature as my gsoc project. Could you pls assign me a layer I could work on.

**Comment by morevnaproject** [comment]
Hi @amanbora! This feature is already got first prototype and quite a competition around. I encourage you to choose a different project from our Ideas List - https://synfig-docs-dev.readthedocs.io/en/latest/gsoc/2019/ideas.html - ore come up with your own idea. Thank you! ^__^

**Comment by LaPingvino** [comment]
Telegram's new TGS format (https://telegram.org/blog/animated-stickers/) seems to be a variant of Lottie JSON compressed with GZ... because they have very specific restrictions, it might be relatively easy to get this implemented on top of your work?

**Comment by AnishGG** [comment]
> Telegram's new TGS format (https://telegram.org/blog/animated-stickers/) seems to be a variant of Lottie JSON compressed with GZ... because they have very specific restrictions, it might be relatively easy to get this implemented on top of your work?

Yes, this seems to be a viable option. I will explore this furthur when I get more time(won't be able to focus on two things together). Or it will be much appreciated if someone can explore this option in the mean time.

**Comment by mbasaglia** [comment]
I'm interested in telegram sticker export as well, I'll be testing out adding support for that myself

**Comment by mbasaglia** [comment]
It was easy enough, I've made very minor changes to the lottie exporter to export tgs, my fork of the plugin is in here: https://gitlab.com/mattia.basaglia/tgs/tree/master/synfig

**Comment by AnishGG** [comment]
> It was easy enough, I've made very minor changes to the lottie exporter to export tgs, my fork of the plugin is in here: https://gitlab.com/mattia.basaglia/tgs/tree/master/synfig

This is great! I myself have never dealt with telegram before, so I might not be able to test it. 
But I guess this feature would be awesome!
@morevnaproject your views regarding this please. ^__^

**Comment by morevnaproject** [comment]
This is **absolutely** exciting! ^__^

**Comment by LaPingvino** [comment]
@mbasaglia can you give an example output file so I can test if my Telegram picks it up independently?

**Comment by mbasaglia** [comment]
@LaPingvino 
Here's a test file (Note: I had to add the gz suffix to upload it to github, for telegram remove ".gz" from the file name, without extracting it)
[test.sifz.D35E47A0.tgs.gz](https://github.com/synfig/synfig/files/3366875/test.sifz.D35E47A0.tgs.gz)

Also keep in mind currently the Lottie exporter is very basic so it can't yet be used to export anything but the most trivial shapes and animations.

I already have utility scripts in the same repo I've linked above. I'm also working on a python library based off the Lottie json schema

**Comment by mbasaglia** [comment]
Quick question: What kind of reference/documentation has been used to describe the lottie format for exporting from synfig? I see some discrepancies between the json schema in the lottie repo and the output from the synfig plugin.
The schema itself seems a bit low quality so I was wondering if there was a better source of info on the format.

**Comment by AnishGG** [comment]
Basically the above mentioned JSoN schema has been used. The keys which are serving no purpose have been removed intentionally. Even the schema has some mistakes in it.
So to be fully sure, you can create the shape/layer in After Effects and use bodymovin plugin to export it to lottie format. This will give you the correct results.

**Comment by AnishGG** [comment]
@mbasaglia 
I had a look at the tgs code on gitlab. I noticed that you cloned the lottie-exporter's part which is merged in the master. It does not support splines yet. 
But the lattest version #756 supports splines. You might want to clone this instead of the previous version

**Comment by mbasaglia** [comment]
thanks, I've subscribed to that PR, I'll keep my version up to date base on that

**Comment by mbasaglia** [comment]
btw, I did a lot of work on making sense of the lottie format so I developed a python framework that can be used to read and write these files. If there's ever the need to import lottie files into synfig my framework is capable of doing so.

**Comment by GraithTiger** [comment]
I've picked up Synfig and have been trying out the lottie exporter, and I've found that it fails on this file:
[noises_graithtiger.zip](https://github.com/synfig/synfig/files/3413076/noises_graithtiger.zip), giving the error:

````
Traceback (most recent call last):
  File "lottie-exporter.py", line 161, in <module>
    new_file_name = parse(FILE_NAME)
  File "lottie-exporter.py", line 66, in parse
    gen_layers(settings.lottie_format["layers"], root, len(root) - 1)
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\layers\driver.py", line 82, in gen_layers
    itr)
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\layers\group.py", line 85, in gen_layer_group
    asset = add_precomp_asset(settings.lottie_format["assets"][-1], canvas[0], len(canvas[0]))
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\sources\precomp.py", line 26, in add_precomp_asset
    layers.driver.gen_layers(lottie["layers"], root, layer_itr-1)
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\layers\driver.py", line 82, in gen_layers
    itr)
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\layers\group.py", line 85, in gen_layer_group
    asset = add_precomp_asset(settings.lottie_format["assets"][-1], canvas[0], len(canvas[0]))
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\sources\precomp.py", line 26, in add_precomp_asset
    layers.driver.gen_layers(lottie["layers"], root, layer_itr-1)
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\layers\driver.py", line 82, in gen_layers
    itr)
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\layers\group.py", line 72, in gen_layer_group
    group.update_pos(pos)
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\synfig\group.py", line 75, in update_pos
    add(waypoint[0], offset)
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\synfig\group.py", line 91, in add
    vector[0].text = str(float(vector[0].text) + offset[0])
ValueError: could not convert string to float: 
````
Looking into it a little it appears that the script is operating on a scalar when it's expecting a vector and erroring out. Adding 
````
if vector.tag != "vector":
    return
````

before the offending line seems to fix that issue, but a similar error crops up later:
````
Traceback (most recent call last):
  File "lottie-exporter.py", line 161, in <module>
    new_file_name = parse(FILE_NAME)
  File "lottie-exporter.py", line 66, in parse
    gen_layers(settings.lottie_format["layers"], root, len(root) - 1)
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\layers\driver.py", line 82, in gen_layers
    itr)
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\layers\group.py", line 85, in gen_layer_group
    asset = add_precomp_asset(settings.lottie_format["assets"][-1], canvas[0], len(canvas[0]))
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\sources\precomp.py", line 26, in add_precomp_asset
    layers.driver.gen_layers(lottie["layers"], root, layer_itr-1)
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\layers\driver.py", line 82, in gen_layers
    itr)
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\layers\group.py", line 85, in gen_layer_group
    asset = add_precomp_asset(settings.lottie_format["assets"][-1], canvas[0], len(canvas[0]))
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\sources\precomp.py", line 26, in add_precomp_asset
    layers.driver.gen_layers(lottie["layers"], root, layer_itr-1)
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\layers\driver.py", line 82, in gen_layers
    itr)
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\layers\group.py", line 76, in gen_layer_group
    gen_helpers_transform(lottie["ks"], layer.get_layer(), pos[0], anchor[0], scale[0], angle[0], opacity[0])
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\helpers\transform.py", line 53, in gen_helpers_transform
    index.inc())
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\properties\multiDimensionalKeyframed.py", line 32, in gen_properties_multi_dimensional_keyframed
    gen_properties_offset_keyframe(lottie["k"], animated, i)
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\properties\offsetKeyframe.py", line 353, in gen_properties_offset_keyframe
    cur_pos = parse_position(animated, i)
  File "G:\Program Files\Synfig\share\synfig\plugins\lottie-exporter\common\misc.py", line 90, in parse_position
    pos = [float(animated[i][0][0].text),
ValueError: could not convert string to float: 
````

and it's seeming to fail on this part of the xml:
````
<animated type="vector">
  <waypoint time="0s" before="constant" after="constant"><add type="vector">
                        <lhs>
                          <vector>
                            <x>0.0000000000</x>
                            <y>0.0000000000</y>
                          </vector>
                        </lhs>
                        <rhs>
                          <vector>
                            <x>0.0000000000</x>
                            <y>0.0000000000</y>
                          </vector>
                        </rhs>
                        <scalar>
                          <real value="1.0000000000"/>
                        </scalar>
                      </add>
                    </waypoint>
  <waypoint time="0.1s" before="constant" after="constant"><add type="vector">
                        <lhs>
                          <vector>
                            <x>0.0000000000</x>
                            <y>0.0000000000</y>
                          </vector>
                        </lhs>
                        <rhs>
                          <vector>
                            <x>0.0000000000</x>
                            <y>0.0000000000</y>
                          </vector>
                        </rhs>
                        <scalar>
                          <real value="1.0000000000"/>
                        </scalar>
                      </add>
                    </waypoint>
</animated>
````

**Comment by AnishGG** [comment]
> `<add type="vector">`

Convert methods like `add` are not supported yet. These are yet to be implemented.

**Comment by morevnaproject** [comment]
The Lottie exporter now shipped in version 1.3.12 - https://www.synfig.org/2020/02/07/synfig-studio-1-3-12-released/

**Comment by ohlr** [comment]
Two things I noticed:
1. framerate has an impact on filesize but no impact on the framerate when viewed in the browser(chrome).
2. In firefox only the animated frames are shown independent of framerate.

**Comment by AnishGG** [comment]
1. Yes, this is expected, as the shapes and outlines are exported frame by frame using the most basic layer of Lottie, hence increasing the size of the file. This might also lead to a lag in animation on larger displays/screens.
2. I have been using firefox and chrome both for testing but did not face this issue yet. Could you raise an issue mentioning the firefox version as well as the `.sif` file used.

**Comment by ohlr** [comment]
Thanks for the quick response. I realized point 2 is mainly an issue with large/complex files. I think Firefox is just not as good/fast in rendering.

**Comment by fire** [comment]
https://synfig.readthedocs.io/en/latest/releases/stable/1.4.0.html has lottie export.
