### ISSUE TITLE
[Lottie exporter] 075-skeleton-group.sif fails to export

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#927]
**Synfig version & platform**:
Commit id: 7cadfbf

**Issue description**:
Test file - https://github.com/synfig/synfig-tests-regressions/blob/master/export/lottie/075-skeleton-group.sif

Fails to export with the following errors:
```
synfig(17553) [22:17:20] info: Traceback (most recent call last):
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/lottie-exporter.py", line 163, in <module>
    new_file_name = parse(FILE_NAME)
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/lottie-exporter.py", line 68, in parse
    gen_layers(settings.lottie_format["layers"], canvas, canvas.get_num_layers() - 1)
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/layers/driver.py", line 82, in gen_layers
    itr)
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/layers/group.py", line 69, in gen_layer_group
    angle.animate("rotate_layer_angle")
UnboundLocalError: local variable 'angle' referenced before assignment
```

**Comment by AnishGG** [comment]
@morevnaproject, 
Unfortunately bones are not yet ready to handle the group transformations. This might take some more time to resolve.
Before resolving this issue, I will have to dig deeper and develop some new classes like `composite` class.
